import * as blocks from '@aula/pedagogical-ui';
import {
  DiagramaSagital,
  GraficoComparacion,
  GraficoDosCondiciones,
  GraficoFuncion,
  GraficoRectas,
  GraficoSistema,
  MaquinaFuncion,
  RectaIntervalos,
} from '@aula/interactives';

/** Componentes registrados para el MDX; validate-mdx usa la misma lista. */
export const mdxComponents = {
  Definicion: blocks.Definicion,
  Objetivo: blocks.Objetivo,
  Comprobacion: blocks.Comprobacion,
  Tarjeta: blocks.Tarjeta,
  Paneles: blocks.Paneles,
  Etiquetas: blocks.Etiquetas,
  Etiqueta: blocks.Etiqueta,
  Asociacion: blocks.Asociacion,
  Composicion: blocks.Composicion,
  Propiedad: blocks.Propiedad,
  Teorema: blocks.Teorema,
  EjemploResuelto: blocks.EjemploResuelto,
  PracticaGuiada: blocks.PracticaGuiada,
  ErrorTipico: blocks.ErrorTipico,
  PracticaIndividual: blocks.PracticaIndividual,
  Cierre: blocks.Cierre,
  Columnas: blocks.Columnas,
  Paso: blocks.Paso,
  Formula: blocks.Formula,
  PreguntaPAES: blocks.PreguntaPAES,
  GraficoSistema,
  GraficoDosCondiciones,
  GraficoRectas,
  GraficoFuncion,
  GraficoComparacion,
  RectaIntervalos,
  DiagramaSagital,
  MaquinaFuncion,
  MascotaProfePina: blocks.MascotaProfePina,
};
